import SwiftUI

/// Small badge overlay showing whether an image was imported or AI-generated
struct ImageSourceIndicatorView: View {
    let source: ImageSource

    var body: some View {
        HStack(spacing: 4) {
            Image(systemName: iconName)
                .font(.system(size: 10))
            Text(label)
                .font(.system(size: 10, weight: .medium))
        }
        .padding(.horizontal, 6)
        .padding(.vertical, 3)
        .background(backgroundColor)
        .foregroundColor(.white)
        .cornerRadius(4)
        .accessibilityLabel(accessibilityText)
    }

    private var iconName: String {
        switch source {
        case .imported: return "square.and.arrow.down"
        case .generated: return "sparkles"
        }
    }

    private var label: String {
        switch source {
        case .imported: return "Imported"
        case .generated: return "Generated"
        }
    }

    private var backgroundColor: Color {
        switch source {
        case .imported: return .green
        case .generated: return .blue
        }
    }

    private var accessibilityText: String {
        switch source {
        case .imported: return "Image imported from external file"
        case .generated: return "Image generated by AI"
        }
    }
}
